import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Times-Roman",
    fontSize: 11,
    color: "#2C2416",
    backgroundColor: "#FFFFFF",
  },
  pageA5: {
    padding: 30,
    fontFamily: "Times-Roman",
    fontSize: 10,
    color: "#2C2416",
    backgroundColor: "#FFFFFF",
  },
  header: {
    textAlign: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#D4C5B2",
    paddingBottom: 12,
  },
  churchName: {
    fontSize: 14,
    fontFamily: "Times-Bold",
    marginBottom: 4,
  },
  serviceTitle: {
    fontSize: 18,
    fontFamily: "Times-Bold",
    marginBottom: 4,
  },
  dateText: {
    fontSize: 11,
    color: "#6B5D4D",
    marginBottom: 2,
  },
  seasonBadge: {
    fontSize: 9,
    color: "#6B5D4D",
    marginTop: 4,
  },
  section: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Times-Bold",
    marginBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#D4C5B2",
    paddingBottom: 3,
  },
  slotRow: {
    flexDirection: "row",
    marginBottom: 4,
    paddingLeft: 8,
  },
  slotLabel: {
    width: 120,
    fontSize: 10,
    fontFamily: "Times-Bold",
  },
  slotValue: {
    flex: 1,
    fontSize: 10,
  },
  readingRow: {
    flexDirection: "row",
    marginBottom: 3,
    paddingLeft: 8,
  },
  readingLabel: {
    width: 80,
    fontSize: 10,
    fontFamily: "Times-Italic",
  },
  readingValue: {
    flex: 1,
    fontSize: 10,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#6B5D4D",
    borderTopWidth: 0.5,
    borderTopColor: "#D4C5B2",
    paddingTop: 6,
  },
  collectText: {
    fontSize: 10,
    fontFamily: "Times-Italic",
    paddingLeft: 8,
    marginBottom: 8,
    lineHeight: 1.4,
  },
});

export interface ServiceSheetData {
  churchName: string;
  serviceType: string;
  date: string;
  liturgicalName: string;
  season: string;
  colour: string;
  collect?: string;
  readings: { position: string; reference: string }[];
  musicSlots: {
    label: string;
    value: string;
    notes?: string;
  }[];
  format?: "A4" | "A5";
  logoUrl?: string;
}

export function ServiceSheetDocument({ data }: { data: ServiceSheetData }) {
  const isA5 = data.format === "A5";
  const pageSize = isA5 ? "A5" : "A4";
  const pageStyle = isA5 ? styles.pageA5 : styles.page;

  const serviceTypeLabel: Record<string, string> = {
    SUNG_EUCHARIST: "Sung Eucharist",
    CHORAL_EVENSONG: "Choral Evensong",
    SAID_EUCHARIST: "Said Eucharist",
    CHORAL_MATINS: "Choral Matins",
    FAMILY_SERVICE: "Family Service",
    COMPLINE: "Compline",
    CUSTOM: "Service",
  };

  return (
    <Document>
      <Page size={pageSize} style={pageStyle}>
        <View style={styles.header}>
          <Text style={styles.churchName}>{data.churchName}</Text>
          <Text style={styles.serviceTitle}>
            {serviceTypeLabel[data.serviceType] || data.serviceType}
          </Text>
          <Text style={styles.dateText}>{data.liturgicalName}</Text>
          <Text style={styles.dateText}>{data.date}</Text>
          <Text style={styles.seasonBadge}>
            {data.season} — {data.colour}
          </Text>
        </View>

        {data.collect && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Collect</Text>
            <Text style={styles.collectText}>{data.collect}</Text>
          </View>
        )}

        {data.readings.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Readings</Text>
            {data.readings.map((r, i) => (
              <View key={i} style={styles.readingRow}>
                <Text style={styles.readingLabel}>{r.position}</Text>
                <Text style={styles.readingValue}>{r.reference}</Text>
              </View>
            ))}
          </View>
        )}

        {data.musicSlots.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Music</Text>
            {data.musicSlots.map((slot, i) => (
              <View key={i} style={styles.slotRow}>
                <Text style={styles.slotLabel}>{slot.label}</Text>
                <Text style={styles.slotValue}>
                  {slot.value}
                  {slot.notes ? ` (${slot.notes})` : ""}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Precentor — Church Music Planner
        </Text>
      </Page>
    </Document>
  );
}
