import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Packer,
} from "docx";
import type { ServiceSheetData } from "./service-sheet";

export async function generateServiceSheetDocx(
  data: ServiceSheetData
): Promise<Buffer> {
  const serviceTypeLabel: Record<string, string> = {
    SUNG_EUCHARIST: "Sung Eucharist",
    CHORAL_EVENSONG: "Choral Evensong",
    SAID_EUCHARIST: "Said Eucharist",
    CHORAL_MATINS: "Choral Matins",
    FAMILY_SERVICE: "Family Service",
    COMPLINE: "Compline",
    CUSTOM: "Service",
  };

  const children: Paragraph[] = [];

  // Header
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: data.churchName, bold: true, size: 28, font: "Times New Roman" }),
      ],
    })
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: serviceTypeLabel[data.serviceType] || data.serviceType,
          bold: true,
          size: 36,
          font: "Times New Roman",
        }),
      ],
    })
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: data.liturgicalName, size: 22, font: "Times New Roman" }),
      ],
    })
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: data.date, size: 22, font: "Times New Roman", color: "6B5D4D" }),
      ],
    })
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "D4C5B2" } },
      children: [
        new TextRun({ text: `${data.season} — ${data.colour}`, size: 18, font: "Times New Roman", color: "6B5D4D" }),
      ],
    })
  );

  // Collect
  if (data.collect) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Collect", bold: true, size: 24, font: "Times New Roman" })],
      })
    );
    children.push(
      new Paragraph({
        spacing: { after: 200 },
        children: [
          new TextRun({ text: data.collect, italics: true, size: 20, font: "Times New Roman" }),
        ],
      })
    );
  }

  // Readings
  if (data.readings.length > 0) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Readings", bold: true, size: 24, font: "Times New Roman" })],
      })
    );
    for (const reading of data.readings) {
      children.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: `${reading.position}: `, italics: true, size: 20, font: "Times New Roman" }),
            new TextRun({ text: reading.reference, size: 20, font: "Times New Roman" }),
          ],
        })
      );
    }
    children.push(new Paragraph({ spacing: { after: 200 }, children: [] }));
  }

  // Music
  if (data.musicSlots.length > 0) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Music", bold: true, size: 24, font: "Times New Roman" })],
      })
    );
    for (const slot of data.musicSlots) {
      children.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: `${slot.label}: `, bold: true, size: 20, font: "Times New Roman" }),
            new TextRun({ text: slot.value, size: 20, font: "Times New Roman" }),
            ...(slot.notes
              ? [new TextRun({ text: ` (${slot.notes})`, italics: true, size: 18, font: "Times New Roman", color: "6B5D4D" })]
              : []),
          ],
        })
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      spacing: { before: 400 },
      border: { top: { style: BorderStyle.SINGLE, size: 1, color: "D4C5B2" } },
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by Precentor — Church Music Planner",
          size: 16,
          font: "Times New Roman",
          color: "6B5D4D",
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
