import React from "react";
import { Text } from "@react-pdf/renderer";
import type { TemplateLayout } from "@/types/service-sheet";
import type { PdfStyles } from "../create-styles";

interface SheetFooterProps {
  layout: TemplateLayout;
  ccliNumber?: string;
  styles: PdfStyles;
}

export function SheetFooter({ layout, ccliNumber, styles }: SheetFooterProps) {
  const parts = ["Generated by Precentor — Church Music Planner"];
  if (layout.ccliNotice && ccliNumber) {
    parts.push(`CCLI Licence No. ${ccliNumber}`);
  }

  return <Text style={styles.footer}>{parts.join("  |  ")}</Text>;
}
