import type { Metadata } from "next";
import Link from "next/link";
import { BackLink } from "@/components/back-link";

export const metadata: Metadata = {
  title: "Terms of Service — Precentor",
  description: "Terms governing the use of Precentor, the church music planning platform.",
};

export default function TermsPage() {
  return (
    <main id="main-content" className="max-w-2xl mx-auto px-4 py-12 space-y-8">
      <BackLink href="/">Back to home</BackLink>

      <div className="space-y-2">
        <h1 className="text-3xl font-heading font-semibold">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: April 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">1. Acceptance of Terms</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          By creating an account or using Precentor, you agree to these Terms of
          Service. If you do not agree, please do not use the platform.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">2. Description of Service</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Precentor provides tools for church music and service planning,
          including a lectionary calendar, music search and suggestions, choir
          rota management, and service sheet generation. The service is provided
          free of charge for Church of England parishes.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">3. Your Account</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          You are responsible for maintaining the confidentiality of your account
          credentials. You agree to provide accurate information when creating
          your account and to keep it up to date. One person may not create
          multiple accounts.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">4. Acceptable Use</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          You agree to use Precentor only for its intended purpose of church
          service and music planning. You must not use the platform in any way
          that is unlawful, harmful, or that could impair the service for other
          users.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">5. Your Content</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          You retain ownership of any content you create on Precentor (service
          plans, notes, custom text). We do not claim any intellectual property
          rights over your content. You grant us a limited licence to store and
          display your content as needed to provide the service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">6. AI-Generated Suggestions</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Music suggestions are generated by artificial intelligence and are
          provided as recommendations only. You are responsible for reviewing and
          approving all music selections for your services.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">7. Availability</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We aim to keep Precentor available at all times but cannot guarantee
          uninterrupted access. We may suspend the service for maintenance,
          updates, or unforeseen circumstances.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">8. Termination</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          You may delete your account at any time from your account settings. We
          reserve the right to suspend or terminate accounts that violate these
          terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">9. Changes to Terms</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          We may update these terms from time to time. If we make significant
          changes, we will notify you via email. Continued use of the service
          after changes constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-heading font-medium">10. Governing Law</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          These terms are governed by the laws of England and Wales.
        </p>
      </section>

      <div className="border-t border-border pt-6 text-xs text-muted-foreground space-y-1">
        <p>
          See also our{" "}
          <Link href="/privacy" className="underline underline-offset-2 hover:text-foreground">
            Privacy Notice
          </Link>
          .
        </p>
        <p>
          Questions about these terms?{" "}
          <Link href="/contact" className="underline underline-offset-2 hover:text-foreground">
            Contact us
          </Link>
          .
        </p>
      </div>
    </main>
  );
}
