/**
 * Seed the database with Common Worship collects.
 *
 * Loads collect texts from src/data/collects-cw.json (generated by
 * scripts/scrape-collects.ts), matches each entry to a liturgical day by
 * cw_name, and upserts a row into the `collects` table with rite "CW" and
 * churchId null (system record).
 *
 * Also updates the `liturgical_days.collect` column so that a downstream
 * query on that column still works.
 *
 * Idempotent: uses onConflictDoUpdate targeting the unique index
 * (liturgicalDayId, rite, churchId) on the collects table.
 *
 * Usage: npm run db:seed-collects
 *
 * Prerequisites:
 *   Run `npm run db:scrape-collects` first to generate collects-cw.json.
 */

import "dotenv/config";
import * as fs from "fs";
import * as path from "path";
import { db } from "@/lib/db";
import { collects, liturgicalDays } from "@/lib/db/schema-base";
import { eq } from "drizzle-orm";

// ─── Load JSON source ──────────────────────────────────────────────

const JSON_PATH = path.join(process.cwd(), "src/data/collects-cw.json");

function loadCollectsJson(): Record<string, string> {
  if (!fs.existsSync(JSON_PATH)) {
    throw new Error(
      `${JSON_PATH} not found.\n` +
        "Run `npm run db:scrape-collects` first to generate the collect data."
    );
  }
  const raw = fs.readFileSync(JSON_PATH, "utf-8");
  return JSON.parse(raw) as Record<string, string>;
}

// ─── Main ─────────────────────────────────────────────────────

async function main() {
  const collectsJson = loadCollectsJson();
  const cwNames = Object.keys(collectsJson);
  console.log(`Loaded ${cwNames.length} collects from ${JSON_PATH}`);

  // Fetch all liturgical days so we can match by cwName
  const allDays = await db
    .select({ id: liturgicalDays.id, cwName: liturgicalDays.cwName })
    .from(liturgicalDays);

  console.log(`Found ${allDays.length} liturgical days in the database.`);

  let inserted = 0;
  let skipped = 0;

  for (const day of allDays) {
    const collectText = collectsJson[day.cwName];
    if (!collectText) {
      console.warn(`  - No collect for "${day.cwName}" — skipping`);
      skipped++;
      continue;
    }

    // Update liturgical_days.collect column (source of truth for downstream)
    await db
      .update(liturgicalDays)
      .set({ collect: collectText })
      .where(eq(liturgicalDays.id, day.id));

    // Upsert into collects table
    await db
      .insert(collects)
      .values({
        liturgicalDayId: day.id,
        rite: "CW",
        title: `Collect for ${day.cwName}`,
        text: collectText,
        churchId: null,
      })
      .onConflictDoUpdate({
        target: [collects.liturgicalDayId, collects.rite, collects.churchId],
        set: {
          title: `Collect for ${day.cwName}`,
          text: collectText,
        },
      });

    console.log(`  + ${day.cwName}`);
    inserted++;
  }

  console.log(`\nDone. Seeded ${inserted} collects; skipped ${skipped}.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
